### ISSUE TITLE
Add composer support

### ISSUE THREAD

**Issue by ghermans** [bagisto/laravel-aliexpress-dropship#55]
Allow the user to install this extension with composer

### Todo
- [x] Create a composer.json file.
- [ ] Register the package at packagist.
- [x] Update the installation section in the readme file.
